### ISSUE TITLE
Create a contributing.md

### ISSUE THREAD

**Issue by MattMcAdams** [bookiza/toucaan#5]
Hi, I'd love to help out but I'm not sure where to start. I looked for a contributing doc but didn't find one. I'm also kind of new to open source, so let me know if this is a dumb question.

Is there anything you need some help with?
What kind of contributions are you looking for?
What kind of process is there for making a contribution?
Is there a roadmap or specific goals / features?
Will this project use SCSS or pure CSS?
Is there a place to ask questions about / help to get oriented to this project?
How do you set up a development environment for this project?

Thanks! This looks like a really cool and ambitious project, and I hope I can be helpful.

**Comment by marvindanig** [comment]
Hey thanks for offering to help! 

1. I updated the README with a few TODOs. Getting the website for documentation up is critical.

2. All contributions are welcome. Including essays, criticisms and theory on why one pattern is better than the other. I think Toucaan will remain flexible for PRs and it will be a loosely coupled framework than an absolute tight one. Also, not much of a process at this stage. 

3. Next milestone is getting baseline CSS and model responsive typography up. 

4. I have been using SASS/SCSS for past 10 years. I want to use plain CSS on this one just to keep tab on what's happening in there and to avoid deep nesting. 

5. We can set-up a slack channel or discord in a few weeks. 

6. `$ git clone url\to\toucaan` and `$ npm install`. 

I have added the [Contributing Code of Conduct](https://github.com/bookiza/toucaan/blob/master/CONTRIBUTING.md) for this repo, so there is that.
